### ISSUE TITLE
Create NLP Sandbox Rules page

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#12]
Page to edit:

https://github.com/nlpsandbox/nlpsandbox-website-synapse/blob/staging/wiki/RulesResources.md

Notes:
- This is a continuous benchmarking project
- This is not a DREAM challenge

**Comment by ychae** [comment]
@tschaffter would you be able to give me write access to this repo? I don't seem to be able to push any changes.

**Comment by tschaffter** [comment]
@ychae Done. You now have Maintain access to this repo.

**Comment by tschaffter** [comment]
## Update

The Rules page has been updated today. Keeping this ticket open until we figured out the rules for dataset usage.

**Comment by tschaffter** [comment]
https://sagebionetworks.jira.com/browse/SG-3700

**Comment by tschaffter** [comment]
@thomasyu888 I would be interest to hear your feedback about the [project rules](https://github.com/nlpsandbox/nlpsandbox-website-synapse/blob/staging/wiki/604831-Rules.md).

**Comment by thomasyu888** [comment]
The terms look good to me - may be beneficial for someone on governance to look this over as well. One thing Im always curious about is how we enforce these terms.

**Comment by tschaffter** [comment]
@ychae Following [this discussion](https://github.com/nlpsandbox/nlpsandbox-website-synapse/issues/45), can you please update the rules so that we no longer request models to be released publicly?

**Comment by tschaffter** [comment]
An initial version of the rules is publicly available.
