### ISSUE TITLE
Update Registration button on Synapse

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#13]
The current registration button (click wrap) has been created a long time ago and I don't remember what it looks like. We need to review it and update it.

This ticket is maybe depending on #12, #14

**Comment by tschaffter** [comment]
Here is the current only page of the registration popup:

![image](https://user-images.githubusercontent.com/3056480/106219022-70760d80-618d-11eb-8ec0-da3597681f4b.png)

**Comment by thomasyu888** [comment]
The clickwrap is something only the governance team can help us with.

**Comment by ychae** [comment]
@thomasyu888  is correct. @tschaffter have you reached out to someone on the governance team about this? If not, I can do so.

**Comment by ychae** [comment]
Email sent to Ann

**Comment by ychae** [comment]
Tracking in JIRA: https://sagebionetworks.jira.com/browse/SG-3700

**Comment by ychae** [comment]
@tschaffter and @thomasyu888 please edit this copy below (or point me to where I can find additional information) for the updated click-wrap:

> Actions taken while participating in the NLP-Sandbox Continuous Benchmarking Project are visible to others. This includes uploading files, editing wikis, posting in discussion forums, and submissions.

> Please note that participants must abide by the guiding principles for responsible research use and data handling within the Synapse Commons Platform as described in the [Synapse Governance documents](https://docs.synapse.org/articles/governance.html).

> **Anonymous Challenge Participant Profile**

> To participate anonymously:

> 1. Use the button below to edit your profile (link opens in a new window).
> 2. Change your username to something that you feel is anonymous.
> 3. Clear all of the other entries in your profile.

**Comment by tschaffter** [comment]
Replace the paragraph

> Actions taken while participating in the NLP-Sandbox Continuous Benchmarking Project are visible to others. This includes uploading files, editing wikis, posting in discussion forums, and submissions.

by

> Actions taken while participating in the NLP Sandbox Project are visible to others. This includes uploading files, editing wikis, posting in discussion forums, and submissions.

The rest looks good!

**Comment by tschaffter** [comment]
@ychae After thinking about it, I don't want to encourage the users of the NLP Sandbox to participate anonymously. Can this information be removed from the click wrap?

**Comment by ychae** [comment]
@tschaffter I don't see why not! I'll add the updated text to the JIRA ticket.

**Comment by ychae** [comment]
And by add, I mean remove the Anonymous participant section 😅

**Comment by ychae** [comment]
I've started a [doc](https://docs.google.com/document/d/1GsVVMWcbH4gfPXAuhUF0UfRhDVbUl8cX_oqrsIxQSkc/edit#heading=h.5of66iuo2r3t) on what the possible process could be to update the click-wrap in the future if needed.

**Comment by tschaffter** [comment]
The current registration should be fine. Will reopen if there is an issue later when using it on the production site.
