### ISSUE TITLE
The size of the column 'submission_status' is too small. The column size needs to be at least 22 characters.

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#136]
Just submitted to the contact annotation queue. I get this message on the [dashboard page](https://www.synapse.org/#!Synapse:syn22277123/wiki/611539).

![image](https://user-images.githubusercontent.com/3056480/124637313-6fcd5b80-de3e-11eb-8638-11c1e7708b47.png)
![image](https://user-images.githubusercontent.com/3056480/124637396-9095b100-de3e-11eb-9a0d-42131719bb3a.png)

**Comment by tschaffter** [comment]
Same behavior on the Id and Covid annotation dashboard.

**Comment by thomasyu888** [comment]
Fixed
