### ISSUE TITLE
Create Submission Overview Dashboard using flexdashboard

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#152]
Create a dashboard that includes statistics about the tools evaluated in the NLP Sandbox. Example of metrics include:

General stats:

- Number of unique submitters
- Number of tasks / benchmarks open
- Latest version of the NLP Sandbox schemas
- Number of datasets / data sites
- Number of unique tools (e.g. using the `Tool.name`)
- Programming languages used by the tools (would need to add `Tool.language`) 
- Other

Notes:

- Same metrics as above but for specific tasks.
- The dashboard is an HTML page that can be generated periodically on GitHub and stored on GitHub Pages and Synapse (if required to include the page in a Synapse Wiki page)
- Another dashboard could be created for the [Monument of NLP Heroes](https://www.synapse.org/#!Synapse:syn22277123/wiki/604824)

### References

- [GA4GH-DREAM Workflow Execution Challenge - Participation Overview](https://www.synapse.org/#!Synapse:syn8507133/wiki/451415)

**Comment by tschaffter** [comment]
The dashboard will be developed in [this repository](https://github.com/nlpsandbox/participation-dashboard).

**Comment by tschaffter** [comment]
@jiaxinmachine88 Could you please create a document to track what we want to go in this participation dashboard? Maybe a google docs with a section for each metrics. Each section should provide at least the following information:
- Name of the metric (e.g. `Tools`)
- Description of the metric (e.g. `Number of unique tools`)
- How to compute the metric value (e.g. `From submission X, count the number of submissions with a unique tool name`)

**Comment by andrewelamb** [comment]
I'm going with these assumptions for now, feel free to correct:

"Number of unique submitters"

unique(submitterid)

"Number of tasks / benchmarks open"

Could you elaborate? Something to do with the status column?

"Latest version of the NLP Sandbox schemas"

Could you elaborate?

"Number of datasets / data sites"

unique(dataset_name) Could you elaborate on data sites?

"Number of unique tools (e.g. using the Tool.name)"

unique(tool_name)

"Programming languages used by the tools (would need to add Tool.language)"

I assume this will be added?

**Comment by tschaffter** [comment]
@andrewelamb 

> Number of tasks / benchmarks open

We could use the number of unique evaluation ID listed in [this table](https://www.synapse.org/#!Synapse:syn23633030/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIzNjMzMDMwIiwgInNlbGVjdGVkRmFjZXRzIjpbeyJjb25jcmV0ZVR5cGUiOiJvcmcuc2FnZWJpb25ldHdvcmtzLnJlcG8ubW9kZWwudGFibGUuRmFjZXRDb2x1bW5WYWx1ZXNSZXF1ZXN0IiwgImNvbHVtbk5hbWUiOiJldmFsdWF0aW9uaWQiLCAiZmFjZXRWYWx1ZXMiOltdfV0sICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNSwgInNvcnQiOlt7ImNvbHVtbiI6ImNyZWF0ZWRPbiIsICJkaXJlY3Rpb24iOiJERVNDIn1dfQ==) (left side).

> Latest version of the NLP Sandbox schemas

The services and tools of the NLP Sandbox are based on the [NLP Sandbox Schemas](https://github.com/nlpsandbox/nlpsandbox-schemas). The latest version number could be retrieved from GitHub API. Alternatively, I'm OK adding a file `.nlpsandbox-version` to this repo with the schemas version `x.y.z`. Here is [an example of this file](https://github.com/nlpsandbox/date-annotator-example/blob/main/.nlpsandbox-version) hosted in another GH repo.

> "Number of datasets / data sites"

When an NLP developer submits a tool, this tool is evaluated on data hosted at different physical location (data sites). Currently there are two data sites enabled (Sage and Medical College of Wisconsin (MCW)). For now we can use a static value (`2`).

The number of datasets can be obtained from the above table as `length(unique(dataset_name))`.

> "Programming languages used by the tools (would need to add Tool.language)"
> I assume this will be added?

Yes

**Comment by andrewelamb** [comment]
![Screenshot from 2021-08-20 09-43-26](https://user-images.githubusercontent.com/7220713/130266664-bc3b5437-224b-4688-97b3-a36e77e70f15.png)

**Comment by andrewelamb** [comment]
![Screenshot from 2021-08-20 10-05-54](https://user-images.githubusercontent.com/7220713/130269103-3d15a429-2c30-4a1d-a149-d12498e071b7.png)

**Comment by tschaffter** [comment]
@andrewelamb The number of tasks open (.i.e. evaluation queues) is incorrect. I could 6 evaluations queues on the table page. The rest looks good!

**Comment by andrewelamb** [comment]
@tschaffter Yep, I was grabbing the wrong column. Thta's been fixed.

**Comment by andrewelamb** [comment]
@tschaffter Would it be all right to use @thomasyu888's credentials for the docker image? He would need read permission to [the source table](https://www.synapse.org/#!Synapse:syn23633030/tables/) and edit permission to the directory we would want to store the html output file.

**Comment by tschaffter** [comment]
@andrewelamb Where is the Docker container going to run? We have a bot account that we can use for this task. I'll create the token and share it with you using our favorite password manager.

**Comment by andrewelamb** [comment]
@tschaffter, I don't have an answer to either of those questions. :) @thomasyu888 ?

**Comment by thomasyu888** [comment]
@tschaffter It will run on our kubernetes cluster and it will need to be a Synapse PAT with download permissions.

**Comment by tschaffter** [comment]
Sounds good!

**Comment by gkowalski** [comment]
See https://github.com/Sage-Bionetworks/SynapseWorkflowOrchestrator/issues/31

**Comment by tschaffter** [comment]
Closing this issue in favor of smaller issues to be created in repository of the dashboard: https://github.com/nlpsandbox/participation-dashboard
