### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#18]
- For GH
- For DockerHub
- For Synapse Project/Team
- For Discord

**Comment by tschaffter** [comment]
https://sagebionetworks.jira.com/browse/DESIGN-377

**Comment by tschaffter** [comment]
### TODO

- [x] Ask Stockard to render black and white logo using [simpleicons](https://simpleicons.org/) image spec used in badges.

**Comment by jiaxinmachine88** [comment]
Updated Jira ticket with comments around (1) preference for #1 and (2) need for b+w logo render using simple icons 

https://sagebionetworks.jira.com/browse/DESIGN-377

**Comment by tschaffter** [comment]
Done
