### ISSUE TITLE
Add CI/CD to automatically push pages to staging

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#2]
The idea is to enable review of changes and track most of the actions that we perform manually when updating a production project website on Synapse.

Suggestion:
- Pushing to `staging` automatically push the content of the folder `pages` to the staging site on Synapse
- Pushing to `main` automatically push the content of the folder `pages` to the production site on Synapse

Add protection to the branches `staging` and `main` to restrict who can push to these branches.

**Comment by tschaffter** [comment]
Actually concerning the private internal pages that we are used to have on the staging site and not on the production site: if we want to keep them, we don't want the production branch (main) to be identical to the staging branch. Instead, we could discard the use of the branch (main) - or use it for the staging site - and rely on the creation of Releases to update the production site. When a release is created, run the `mirror-wiki` command to update the production site.

@thomasyu888 Do you see any issues with this second approach that would allow us to keep using private internal pages on staging?

**Comment by tschaffter** [comment]
Could the command `download-wiki` be added to the official release of `challengeutils`, if you consider it mature enough? This would simplify the CI/CD workflow instead of having to clone a specific branch or commit. Alternatively we could create a docker image.

**Comment by tschaffter** [comment]
> Actually concerning the private internal pages that we are used to have on the staging site and not on the production site

Unless absolutely needed, I would like to keep this repo public for transparency and use as an example in future projects. Therefore we must not include private information in the `Internal` section of the pages because this information would still be public in this repo.

**Comment by thomasyu888** [comment]
> @thomasyu888 Do you see any issues with this second approach that would allow us to keep using private internal pages on staging?

No issues with the second approach. I tend to like the staging site as we still most likely need to view things in Synapse prior to releasing it to the public.

> Could the command download-wiki be added to the official release of challengeutils, if you consider it mature enough?

I can work on adding this to the release.

**Comment by tschaffter** [comment]
I reopen this ticket because the PR merge failed. I'll investigate what the issue is.
