### ISSUE TITLE
Describe the 2014 i2b2 dataset

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#32]
Describe the 2014 i2b2 dataset here:
https://github.com/nlpsandbox/nlpsandbox-website-synapse/blob/staging/wiki/608223-2014i2b2NLPDeidChallengeDataset.md

Provide a short paragraph describing the history and content of the dataset, number of notes in the training and evaluation dataset (it's public information), include References section with a few references to papers, website, etc.

**Comment by yy6linda** [comment]
Hi Thomas, I send a [PR](https://github.com/nlpsandbox/nlpsandbox-website-synapse/pull/38) for this issue. However I don't have permission to assign a reviewer.

**Comment by tschaffter** [comment]
Done in #39
