### ISSUE TITLE
Submit examples using the Organizers team

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#36]
@thomasyu888 Organizers are not fair game when it comes to ask Synapse users to join your team. :)

![image](https://user-images.githubusercontent.com/3056480/107282032-52bb6a80-6a0f-11eb-8373-f9e49e07a4ac.png)

What about:

- We register the organizer team to the challenge (this will remove us from the list of available participants)
- Submit the example tools using our organizers team. This way it will be clear that the leaderboard entry is ours and not from an unknown character called @thomasyu888!

**Comment by thomasyu888** [comment]
😆 Great idea @tschaffter :  can you give me manager access to this team: https://www.synapse.org/#!Team:3413390

**Comment by tschaffter** [comment]
Done
