### ISSUE TITLE
Add dataset name and version, and tool license to leaderboard tables

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#42]
### Is your proposal related to a problem?

Each leaderboard table have a column called `Dataset Version`. The value display in this column is the concatenation of a dataset name (e.g. "2014-i2b2") and version (e.g. "20201203").

### Describe the solution you'd like

We want to be able to filter separately by dataset name and dataset version. MCW is working on preparing a private dataset that will be hosted on their own data node. Ideally we should support the case where one data hosting site can evaluate one submission on more than one dataset. For example, we may shutdown Sage Data Hosting site one day and move the i2b2 dataset to MCW data hosting site.

**Comment by tschaffter** [comment]
Here are information that we want to surface in the leaderboard table or on the website

### Dataset name and version

Two pieces of information that we want to use to explore/filter submissions

### Dataset schema version

It is important to know the version of the schemas used by the dataset, but not to explore submissions. The dataset schema version could be specified in the changelog of the dataset. For example, we would say that the dataset "awesome-dataset" version "2020-02-15" implements the NLP Sandbox schemas version x.y.z.

### Submitted tool schema version

This information could have several use:

- Check the tool API version before evaluating its performance. We could specify to the controller that for the dataset "awesome-dataset" version "2020-02-15" relies on the NLP Sandbox schemas "x.y.z" and that tools evaluated on it must implement this version of the schemas.
- A user of the PHI Deidentifier may want to replace its tool dependencies by the best-performing tool. This user would look at the leaderboard table for the Date Annotation task, for example, and look for a tool that implement the Date Annotator API version that the PHI Deidentifier uses.

### Tool license

This is a neat information to show in the leaderboard table

### More

It would be nice to annotate the submission entities with the metadata returned by `/api/v1/tool`, for example for future more comprehensive tool exploration/filtering. The metadata properties would be named using a common prefix.

**Comment by thomasyu888** [comment]
Workflow inputs:

dataset_name: 2014-i2b2
dataset_version: 2013...
api_version: 1.0.0
