### ISSUE TITLE
Create nlpsandbox.io redirections

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#44]
- nlpsandbox.io -> production site
- nlpsandbox.io/videos -> YouTube channel/playlist?
- nlpsandbox.io/tools/phi-deidentifier -> PHI deidentifier app
- discord.nlpsandbox.io -> discord server

**Comment by tschaffter** [comment]
@thomasyu888 I'll look at how to take care of these general redirections (see above).

Regarding the user of nlpsandbox.io and the CF template(s) deployed to SciComp, Xa said:

> The only thing you can do in Route53 is point to a host (i.e. it does not deal with the path). If you need to hit another site with no path, a CNAME should do (e.g. mysite.nlpsnadbox.org ==> mysite.albxxx.amazonaws.com, that's not a redirect it's just going through). To redirect depending on path, you need an endpoint at nlpsandbox.io that will respond with an HTTP 30x (redirect code) and send you to the correct address depending on the request (or in your case the path specified in the request. It can be a small app running on a server, a lambda@edge, or rules on an ALB (I think) or maybe on a Cloudfront distribution (not sure about that one). I would look at lambda@edge so you don't have to setup another server, example, see: https://aws.amazon.com/blogs/networking-and-content-delivery/handling-redirectsedge-part1/.

**Comment by tschaffter** [comment]
Also add https://www.nlpsandbox.io/tools/date-annotator/leaderboards and similar ones

**Comment by tschaffter** [comment]
I successfully set redirects using Route 53 and S3 buckets after reading [this article](https://www.fernandomc.com/posts/serverless-domain-forwarding-aws/).

Current redirects:
nlpsandbox.io => https://github.com/nlpsandbox/nlpsandbox-schemas
www.nlpsandbox.io => https://github.com/nlpsandbox/nlpsandbox-schemas

Unfortunately there is an issue while redirecting to Synapse because of the way Synapse resolves its path.

The following redirects do not work:

- to synapse.org/nlpsandbox
- to synapse.org/#!Synapse:syn22277123

![image](https://user-images.githubusercontent.com/3056480/110414948-c91aaf00-8045-11eb-83d7-2b9d69ab4761.png)

Currently, setting nlpsandbox.io to redirect to synapse.org/nlpsandbox so I can show this behavior to the Synapse Team.

**Comment by tschaffter** [comment]
See https://sagebionetworks.jira.com/browse/PLFM-6630

**Comment by tschaffter** [comment]
- [ ] Enable HTTPS redirects (currently only works with HTTP)

EDIT: I just requested a certificate for `nlpsandbox.io` and `www.nlpsandbox.io` in AWS Certificate Manager.

**Comment by jay-hodgson** [comment]
Not sure if I'm following, but does it work if you redirect to www.synapse.org/nlpsandbox ? (Skip the www redirect)

**Comment by tschaffter** [comment]
The configuration of the redirections in AWS is tracked in this [Jira ticket](https://sagebionetworks.jira.com/browse/PLFM-6630).

**Comment by tschaffter** [comment]
S3 bucket configuration for nlpsandbox.io (another bucket is required for www.nlpsandbox.io):

![image](https://user-images.githubusercontent.com/3056480/111078760-5598f780-84b4-11eb-9baf-2926e45b1519.png)

```json
[
    {
        "Redirect": {
            "HostName": "www.synapse.org",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "#!Synapse:syn22277123"
        }
    }
]
```

**Comment by tschaffter** [comment]
This redirections work when using the full s3 bucket URL, e.g.

- http://nlpsandbox.io.s3-website-us-west-1.amazonaws.com
- http://nlpsandbox.io.s3-website-us-west-1.amazonaws.com/tools/date-annotator/leaderboard

```
[
    {
        "Condition": {
            "KeyPrefixEquals": "tools/date-annotator/leaderboard"
        },
        "Redirect": {
            "HostName": "www.synapse.org",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "#!Synapse:syn22277123/wiki/608544"
        }
    },
    {
        "Redirect": {
            "HostName": "www.synapse.org",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "nlpsandbox"
        }
    }
]
```

However the following redirection does not work as it redirects to google.com, which is a domain name I set earlier today in the configuration of an s3 bucket but I have removed it since. It seems that my browser, router, and/or CloudFront are caching the result.

https://nlpsandbox.io/tools/date-annotator/leaderboard

**Comment by tschaffter** [comment]
I tried with my phone connected to the cellular network and the above url still redirects to google, so it seems that the results is cached by AWS/CloudFront.

**Comment by tschaffter** [comment]
I used [this solution](https://stackoverflow.com/a/63238713) to invalidate the content of the cache of the CloudFront distribution. The redirection works as expected now.

**Comment by tschaffter** [comment]
I also added a redirection for our discord server. Here is the configuration of the S3 buckets `nlpsandbox.io` and `www.nlpsandbox.io`:

```
[
    {
        "Condition": {
            "KeyPrefixEquals": "tools/date-annotator/leaderboard"
        },
        "Redirect": {
            "HostName": "www.synapse.org",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "#!Synapse:syn22277123/wiki/608544"
        }
    },
    {
        "Condition": {
            "KeyPrefixEquals": "tools/person-name-annotator/leaderboard"
        },
        "Redirect": {
            "HostName": "www.synapse.org",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "#!Synapse:syn22277123/wiki/608545"
        }
    },
    {
        "Condition": {
            "KeyPrefixEquals": "tools/physical-address-annotator/leaderboard"
        },
        "Redirect": {
            "HostName": "www.synapse.org",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "#!Synapse:syn22277123/wiki/608546"
        }
    },
    {
        "Condition": {
            "KeyPrefixEquals": "discord"
        },
        "Redirect": {
            "HostName": "discord.gg",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "Zb4ymtF"
        }
    },
    {
        "Redirect": {
            "HostName": "www.synapse.org",
            "HttpRedirectCode": "307",
            "Protocol": "https",
            "ReplaceKeyWith": "nlpsandbox"
        }
    }
]
```

**Comment by tschaffter** [comment]
### Update 2021-05-26

About redirections, the final solution uses a single S3 bucket named nlpsandbox.io . Route 53 has two A records, nlpsandbox.io and www.nlpsandbox.io that both redirect to the CloudFront distribution connected to the S3 bucket.
