### ISSUE TITLE
Increase the size of the latex equation

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#55]
### Is your proposal related to a problem?

The equation that describes the precision, recall and F1 score are too small to be read.

![image](https://user-images.githubusercontent.com/3056480/108644146-a9d72b80-7462-11eb-8b7a-f2b2aaf6aac1.png)

### Describe the solution you'd like

Increase the size of the equations

Synapse page: https://www.synapse.org/#!Synapse:syn24982039
The change must be made to [this markdown file](https://github.com/nlpsandbox/nlpsandbox-website-synapse/blob/staging/wiki/608037-PHIAnnotationDeIdentification.md).

**Comment by thomasyu888** [comment]
Can it be changed? Is this a Jira ticket?

**Comment by tschaffter** [comment]
@yy6linda Tom said that you probably can't increase the font. Instead I'll create image of these equation. I don't mind doing that.

**Comment by thomasyu888** [comment]
@yy6linda and @tschaffter .  I spoke with Jay and he actually brought to my attention there may be ways to change the font size in latex.  We may want to look at latex convention to change the font size.
