### ISSUE TITLE
Update CI/CD workflow to rely on bot personal access token instead of API key

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#58]
### Is your proposal related to a problem?

Using personal access token is preferred to using API key for security reason.

### Describe the solution you'd like

1. Using the bot account, create a token
2. Update the CI/CD workflow to use the token

**Comment by thomasyu888** [comment]
Soon the synapsePythonClient will support this method.  For now it is blocked.

**Comment by tschaffter** [comment]
@thomasyu888 I think that the latest version of the Synapse client for Python now supports PAT. We should now be able to use PAT with challengeutils since it depends on [synapseclient>=2.3.0](https://github.com/Sage-Bionetworks/challengeutils/blob/c92c4712adcaf6ba5f571cd7a061aa86195c9772/setup.py#L32).

**Comment by tschaffter** [comment]
The workflow is stuck when trying to use PAT..

![image](https://user-images.githubusercontent.com/3056480/114789890-a8c2cc00-9d38-11eb-81e7-b3b492499914.png)

**Comment by tschaffter** [comment]
Running the push command locally using the bot PAT works fine..

```console
$ challengeutils push-wiki syn22277124
Wiki updated: homepage
no updates: Stakeholders
no updates: NLP Developers
no updates: NLP Users
no updates: Partner Organizations
no updates: Tasks
no updates: PHI Annotation & De-Identification
Wiki updated: Symptom Annotation
no updates: Users & Teams
no updates: How to Participate
no updates: Create a Synapse Environment
no updates: Develop an NLP Sandbox Tool
no updates: Benchmark an NLP Sandbox Tool
no updates: Submission Dashboards
no updates: Date Annotation Dashboard
no updates: Person Name Annotation Dashboard
no updates: Physical Address Annotation Dashboard
no updates: Leaderboards
no updates: Date Annotation Leaderboard
no updates: Person Name Annotation Leaderboard
no updates: Physical Address Annotation Leaderboard
no updates: Datasets
no updates: 2014 i2b2 NLP De-id Challenge Dataset
no updates: Medical College of Wisconsin De-id Dataset
Wiki updated: Mayo Clinic De-id Dataset
no updates: Resources
no updates: Rules
no updates: Admin
no updates: Physical Address Annotation Admin
no updates: Date Annotation Admin
no updates: Person Name Annotation Admin
no updates: Submission Logs
```

**Comment by tschaffter** [comment]
@thomasyu888 The solution to the above problem was to remove the double quotes around the username and authtoken.
