### ISSUE TITLE
Add information about compute resources available to Docker containers

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#79]
### Is your proposal related to a problem?

Developers currently don't know the CPU and memory resources available to their tools in the benchmarking categories that we support.

### Describe the solution you'd like

For each benchmark, add information about the compute resources available to the Docker container. Here are suggestions:

- CPU: num cores and freq
- Memory: Memory available in GB
- Wall time
- Disk space: we are not providing any for now, will add when requested (e.g. scratch space)
- GPU: none

**Comment by thomasyu888** [comment]
@tschaffter , which page did you want this information? Under "NLP Users" or a new page under "Resources"?

**Comment by tschaffter** [comment]
The page "NLP Users" is meant for the users, not the developers who benchmark. The best place is probably a section that list resources on the page "PHI Annotation and de-identification". That way we can have different resources for different series of tasks.

**Comment by thomasyu888** [comment]
@tschaffter , this could get complicated quickly if each tool could have their own resources, since each site could also have different compute resources.

**Comment by tschaffter** [comment]
You're right. Let's keep is simple for now. Ultimately we should capture the compute resource information in a structure way (metadata). One of the partner organization I met with this week was also interested in tracking the time it take for a method to process N notes.
