### ISSUE TITLE
Add contact annotator information to the Tasks section

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#87]
Follow the example of the existing annotators.

**Comment by tschaffter** [comment]
Depends on https://github.com/nlpsandbox/nlpsandbox/issues/42

**Comment by tschaffter** [comment]
I have an idea to make the page more user-friendly.

**Comment by tschaffter** [comment]
@thomasyu888 Do you know whether we will be launching with ID and Contact support or if we want to enable this tasks a couple of weeks from after launch?

**Comment by thomasyu888** [comment]
@tschaffter I dont see the ID and contact data in the i2b2 version 1 dataset.  Ill look closer again, maybe I'm missing something

**Comment by tschaffter** [comment]
@thomasyu888 You're right, ID and contact annotations didn't end up to the version 1.0.0 of the i2b2 dataset.

**Comment by tschaffter** [comment]
@thomasyu888 Here is the [version 1.1.0 of the i2b2 phi dataset](https://www.synapse.org/#!Synapse:syn25836160).
