### ISSUE TITLE
Review Rules one more time before launch

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#92]
https://www.synapse.org/#!Synapse:syn22277124/wiki/604831

**Comment by jiaxinmachine88** [comment]
Doc link can be found [here](
https://docs.google.com/document/d/1bq-b_G7-1iKoLbewKPj0LXCzqSdsLQziN4Y5Ohf7oAE/edit#heading=h.iv2767ldm99j). Main feedback for @tschaffter to consider: 

**Organization and Structure **
Lots of good content here. Tried to bring relevant bullet points together with these groupings: 

- (1) Registering for NLP Sandbox: more tactical rules that affect developer workflow  
- (2) Publication Considerations: concerning publications 
- (3)  Service Agreement: less tactical rules, more the obligatory legal jargon for scenarios of conflict or malicious intent 

**Consolidating some sections**
- Wondering if we can consolidate some of the below sections, comments in line 

**Terms of Use** 
- Terms of Use currently says, not sure if this is a placeholder for a template we need from governance?  “BE SURE TO CONTACT GOVERNANCE ABOUT THIS PROJECT”

**Comment by jiaxinmachine88** [comment]
A point of consideration for the future: per Meg Doerr's [readability guidelines](https://sagebionetworks.org/wp-content/uploads/2019/01/Primer-on-readability-25April17-1.pdf), I used Microsoft word to get some readability statistics.

The NLP Sandbox rules are currently readable for a college student or graduate. 
If we want to make them readable to a wider audience of Americans, we may want to do a deeper dive on breaking down some of the language. However, given that there is a lot of obligatory legal language here, it may be challenging.

**Comment by tschaffter** [comment]
> The NLP Sandbox rules are currently readable for a college student or graduate.

This sounds like the right audience given that participating requires college student or graduate-level+ software development skills.
