### ISSUE TITLE
Create multi-site compatible leaderboard

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#93]
- [x] Select the columns in the leaderboard (@tschaffter )
- [ ] Implement the leaderboard (@thomasyu888 )

**Comment by thomasyu888** [comment]
@tschaffter You can see a list of columns to choose from here: https://www.synapse.org/#!Synapse:syn23747126/tables/.  This is where SQL joins would be a lot more powerful than what I am doing here...  we also have to think about the addition of new sites.  As new sites get added the leaderboard will get wider and wider.

**Comment by tschaffter** [comment]
@thomasyu888 I keep hesitating between creating a table that has N columns for N data sites. I guess I would like to give it a try in order to be satisfied. Since enabling multi-site evaluation is a powerful contribution of this project, I feel like having a table that show this information in a straightforward way can only help to make our point.

For the date annotator, could you create a table with the following columns:

- `Submission Id`
- `CreatedOn`
- `Submitter`
- `Tool Name`
- `License`
- `i2b2 score`
- `mcw score`

This would be the top leaderboard on the page. Below the table we would show the following information:

- Latest schema version
- Latest version of the i2b2 dataset
- Latest version of the MCW dataset
- What `score` means (here `F1 Instance Strict`)

This top table would only include submission that meet these static information.

Below the top table, we would then have one table per dataset. The table layout would be the same as the one that we currently have on the date annotator leaderboard page.

The proposed design addresses the following needs of the visitor of the page:

1) How does a submission perform across multiple dataset (top table)
2) The visitor may want to download the image of a submission identified in the top table: the easiest way is to copy the value of the submission ID from the top table and search the entire page for this value, leading the visitor to identify the corresponding rows in the detailed table for each dataset, which list the docker repository and digest. Since we paginate results, we can only hope that the results will be in the first pages for each dataset (does the entire page reload when changing the page of leaderboard?). On the new challenge platform, we would have filter where the submission ID can be inputted, and the content of the page would automatically relead to show only the rows matching the submission ID inputted.

How does that sound?

**Comment by tschaffter** [comment]
@thomasyu888 Can you create a prototype of this top table for the date annotator?

**Comment by thomasyu888** [comment]
@tschaffter Before moving forward, please see the leaderboard on this page as an example: https://www.synapse.org/#!Synapse:syn22277124/wiki/611022

We absolutely don't need to have only one leaderboard,  we could definitely split it up, but it just becomes more cumbersome for individuals to link submissions by submission Id.  (Sort of like how we did it in EHR challenge)
